version: '3.2'

services:
  postgres:
    image: postgres:10
    container_name: hindsite_db
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - '/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock'
      - 'dbdata:/var/lib/postgresql/data'
    restart: on-failure

  hindsite:
    build: .
    image: hindsite
    container_name: hindsite
    ports:
      - '80:8000'
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  dbdata:
